name: R-CMD-check
on: [push, pull_request]
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages("devtools"); devtools::install_deps(dependencies = TRUE)'
      - name: Check package
        run: Rscript -e 'devtools::check()'
      - name: Test package
        run: Rscript -e 'devtools::test()'